### ISSUE TITLE
post_save_listener raises ValueError

### ISSUE THREAD

**Issue by thinkwelltwd** [Opus10/django-pgpubsub#17]
First of all, thank you for this library. It really fits a need that I have. :rocket: 

I did discover that the `post_save_listener` doesn't seem to work, at least if I'm understanding things correctly. The following code:

```python
# channels.py
from pgpubsub.channel import TriggerChannel
@dataclass
class PostTriggerChannel(TriggerChannel):
    model = Post

# listeners.py
from pgpubsub import post_save_listener
@post_save_listener(PostTriggerChannel)
def handle_updated_post(old: Post, new: Post):
    logger.info('Post updated from %s to %s', old, new)
```

raises this traceback:

```
  File "/usr/local/lib/python3.9/dist-packages/pgpubsub/listeners.py", line 34, in post_save_listener
    return _trigger_action_listener(
  File "/usr/local/lib/python3.9/dist-packages/pgpubsub/listeners.py", line 77, in _trigger_action_listener
    trigger=notify_cls(
  File "/usr/local/lib/python3.9/dist-packages/pgtrigger/core.py", line 373, in __init__
    raise ValueError(f'Invalid "operation" attribute: {self.operation}')
ValueError: Invalid "operation" attribute: (OR: UPDATE, INSERT)
```

**Comment by PaulGilmartin** [comment]
@thinkwelltwd Thanks for raising this issue! I must admit I have (clearly) never actually used the `post_save_listener`, so sorry you were the one that had to find out the hard way it wasn't tested properly. Your fix looked good and worked perfectly when I tested it locally, so I went ahead and merged it.

One unrelated thing I encountered when testing locally was that whenever we change the listener decorator on a trigger based channel (e.g. I was testing moving from `post_insert_listener` to `post_save_listener`), we need to remember to run `makemigrations` again as it will change the definition of the trigger. I will need to add a note about this into the docs.

Thank you for the kind words about the library. I'm always interested to know about its various use cases are. If you don't mind sharing, could you give anymore info about what you're using it for/what kind of load the library currently deals with for your use case? If you'd prefer not to share then that's also fine :)

**Comment by PaulGilmartin** [comment]
The version with the fix can be found here: https://pypi.org/project/django-pgpubsub/1.0.1/

**Comment by thinkwelltwd** [comment]
> The version with the fix can be found here: https://pypi.org/project/django-pgpubsub/1.0.1/

Thanks!!

>  we need to remember to run makemigrations again as it will change the definition of the trigger

Good point and worth documenting. I didn't stumble on that because I've been setting `PGTRIGGER_MIGRATIONS = False` and use the management command to handle triggers. Personally, I like that much better than using migrations.


> ...what you're using it for/what kind of load the library currently deals with for your use case? 

Sure. I'm the primary dev for several similar-but-different Django-based console applications for several different types of servers (networking / SSO / app store), with several hundred instances of them running that need to be kept synchronized.

I have one database that's a single source of truth and all other distributed instances sync their records with that server, based on whether or not the record in question belongs on that instance.

So I've made heavy use of [pgtrigger](https://github.com/Opus10/django-pgtrigger) to dynamically apply constraints that are relevant for each system. And [pghistory](https://github.com/Opus10/django-pghistory) has been most useful in tracking down where a given record was originally changed.

I've only recently begun to think about getting synchronizing to happen faster and more reliably.  I needed something that would sync better & faster than scheduled rest API-based jobs. Incorporating an MQTT broker could provide that. And I needed a way to ensure that ALL changes got synced, and what better way than to use Postgres's Listen/Notify to trigger publishing to MQTT. 

So I started looking for Django integration and was delighted to discover that the same men than make `pgtrigger` and `pghistory` also make `pgpubsub`. So now I'm including that in the workflow, and am rather sanguine about the prospects it'll offer.

Some stuff really does belong in the database, and record constraints and notifications of changed values are two such things. The Opus10 project really is doing great work at getting the most out of Postgres & Django, and for that I'm thankful.

Thanks for taking my PR; it's the least I can do to give back. I was planning to open an issue of thanks for the project anyway.

**Comment by PaulGilmartin** [comment]
Amazing! That's really cool to hear about it being used in what sounds like quite a complex architecture. Really happy to hear Opus10 is providing you with so much value. If you have any suggestions for further improvements or new features for this library, please feel free to suggest them any time!
