### ISSUE TITLE
Broken compatibility with django 2.2

### ISSUE THREAD

**Issue by romank0** [Opus10/django-pgpubsub#26]
While django 2.2 compatibility is claimed in the README test fail for django 2.2 with the error that field cannot be imported. I run them with `make full-test-suite` command.

The reason is generic support for `JSONField` was added in django 3.0 and in django 2.2 postgres specific field type should be used.

**Comment by PaulGilmartin** [comment]
Sorry about that! I must have made a mistake when adding which versions are supported. I'll update the README to note that we only support >= 3.0

**Comment by romank0** [comment]
This also requires changes to the tox configuration.

**Comment by romank0** [comment]
I have a fix to bring support for django 2.2 back if this is desirable but I'm having troubles following contribution guide (lint does not work and tests fail on reporting) hence the question if master is the right branch to use.

**Comment by PaulGilmartin** [comment]
Hmm why are the tests/linting failing? Does it give an error? 
Feel free to open a PR against master and I can take a look
