### ISSUE TITLE
Add better support for model migrations in TriggerChannel

### ISSUE THREAD

**Issue by romank0** [Opus10/django-pgpubsub#29]
When the django model is migrated to remove the field from the model in the application which supports zero downtime the following procedure is used:

1. field is marked as nullable
2. all usages of the field in the code is removed (including the definition of the field in the model)
3. field is removed from the DB

Steps 1&2 are usually done in one release and then step 3 is done in a separate release. The rationale is that the old version of the aplication that is run during rolling deployment can still access the field in the DB.

 The problem is that when fields are removed from the models and the listener process tries to process the notifications serialized from the DB these notifications still have the old field and deserializion of the model fails with error like `TypeError: MyExampleModel() got an unexpected keyword argument 'field_to_be_removed'`.

I guess the good option here would be to skip fields in the serialized model which are not defined in the django model. If we are removing the field they are usually empty at this point and are not used by the application in any way so skipping them during deserialization to be used in the listener is safe.

**Comment by PaulGilmartin** [comment]
Great point. I hadn't considered this, despite having going through the exact process you mention of removing fields in production before. I think this could be combined into the fix being discussed in https://github.com/Opus10/django-pgpubsub/issues/27, which would be an overall revamp of how we deserialize trigger based channels. I'll have a think about how to best achieve this in the near future and get back to you.

Out of interest, what are you using this library for :) ? Are you using it in a production env with a decent amount of traffic?

**Comment by romank0** [comment]
We are not using the library yet. I'm evaluating different ways to reliably deliver notifications about DB changes. This library does a lot of what I would want from the ideal solution for the problem at hand but not everything.

**Comment by PaulGilmartin** [comment]
@romank0 Sounds cool! Feel free to suggest any other features you'd like to see in this library - I've been looking for some user feedback on how to best proceed its next phase of development.
