### ISSUE TITLE
Improve logging to improve observability

### ISSUE THREAD

**Issue by romank0** [Opus10/django-pgpubsub#37]
I would like that the library use python's `logging` with appropriate levels so that I can configure delivery of log messages to the logs aggregators, configure alerting based on that etc.

Currently everything is written to stdout which is not ideal.

**Comment by PaulGilmartin** [comment]
Logging is something I've wanted to add since starting this library. Hopefully in the near future I'll have time to add some basic logging options.

**Comment by PaulGilmartin** [comment]
@romank0 do you think we can close this one now, or is there anything else we should add logging wise?

**Comment by romank0** [comment]
Yes, what I meant by this improvement is implemented in #51
