### ISSUE TITLE
Set default_auto_field and add migration

### ISSUE THREAD

**Issue by knyghty** [Opus10/django-pgpubsub#53]
I think it'd be good to set `AppConfig.default_auto_field` and add a migration for this, otherwise apps using this with `settings.DEFAULT_AUTO_FIELD` set to `BigAutoField` - the new default will be constantly generating migrations, which makes it difficult to programmatically ensure migrations are up to date for a project.

**Comment by PaulGilmartin** [comment]
Good spot, thanks for raising. I'll make sure this fix is in the next release :)

**Comment by PaulGilmartin** [comment]
@knyghty I must admit I'm not too familiar with this setting. Is this what you had in mind? https://github.com/Opus10/django-pgpubsub/pull/61/files
It didn't generate a migration (I guess because these apps are already using the AutoField for the primary key).

**Comment by knyghty** [comment]
My understanding is that'll do it yeah.

**Comment by PaulGilmartin** [comment]
Great. I have merged a fix. I'll release it to pypi sometime soon
