### ISSUE TITLE
Official docs broken?

### ISSUE THREAD

**Issue by suspiciousRaccoon** [Opus10/django-pgpubsub#63]
Is there an official docs page for this project? I didn't find anything in the README.md, and when I googled for them the webpage seems to be broken:
https://readthedocs.org/projects/django-pgpubsub/builds/

**Comment by PaulGilmartin** [comment]
The only docs we have are in README.md https://github.com/Opus10/django-pgpubsub/blob/master/README.md.

Unfortunately I have not been able to get 
https://readthedocs.org/projects/django-pgpubsub/builds/ working. I think I need help from Opus10 as it has a framework for automatically uploading to readthedocs, I just don't know what's missing from this project to be included in that. I haven't been able to get a hold of Wes to help out with this.

If you have any idea on how to get this on readthedocs, that would be nice :)

**Comment by PaulGilmartin** [comment]
@suspiciousRaccoon Thanks to @madtools , readthedocs is now working! See https://github.com/Opus10/django-pgpubsub/pulls
